import LocalizedStrings from 'react-native-localization';
export default new LocalizedStrings({
  en: {
    addEditEventAddress: "Address (optional)",
    addEditEventAdminOnly: "Admin only",
    addEditEventAnyoneCanJoin: "Anyone Can Join",
    addEditEventBrowse: "Browse",
    addEditEventCancel: "Cancel",
    addEditEventCategory: "Category",
    addEditEventChatModes: "Chat Mode",
    addEditEventChooseCategory: "Choose Category",
    addEditEventChooseDate: "Choose Date",
    addEditEventCreateEvent: "Create Opportunity",
    addEditEventCreateNewEvent: "Create New Post",
    addEditEventCreateOpportunity: "Create Opportunity",
    addEditEventDescriptionIsRequired: "Description is required",
    addEditEventDescriptionTooShort: "Description should be at least 30 characters",
    addEditEventEditEvent: "Edit Post",
    addEditEventEditOpportunity: "Edit Opportunity",
    addEditEventEndTime: "End Time",
    addEditEventEnterCity: "Enter City",
    addEditEventEnterDescription: "Enter Description",
    addEditEventEnterEventAddress: "Enter Address",
    addEditEventEnterState: "Enter State",
    addEditEventEventDateInvalid: "Post date is invalid",
    addEditEventEventDateInvalidPast: "Post date could not be earlier than today",
    addEditEventEventDescription: "Post Description",
    addEditEventEventSaved: "Post successfully saved",
    addEditEventEventTitle: "Post Title",
    addEditEventHideAdditionalOptions: "Hide additional options",
    addEditEventInternalNotes: "Internal Notes",
    addEditEventInvalidZipCodeError: "Zip Code and City pair is invalid. Please use 'Look Up' to get the correct values.",
    addEditEventJoinCriteria: "Join Criteria",
    addEditEventLocal: "Local",
    addEditEventLocation: "Location",
    addEditEventLookUp: "Look Up",
    addEditEventMembersOnly: "Members Only",
    addEditEventNameIsRequired: "Name is required",
    addEditEventOngoingEvent: "Ongoing Post",
    addEditEventOpenToAll: "Open to all",
    addEditEventOpenToMembers: "Open to members",
    addEditEventOpenToVolunteers: "Open to volunteers",
    addEditEventPeopleNeeded: "People Needed",
    addEditEventPostToFacebook: "Post to Facebook",
    addEditEventPostToFacebookExplanation: "Post to Facebook. Please go to Edit Profile/Facebook tab to configure integration.",
    addEditEventPostalCode: "Postal Code",
    addEditEventPostalCodeInvalidLength: "Postal Code must be between 5-7 characters long.",
    addEditEventPoster: "Poster",
    addEditEventPrivate: "Private",
    addEditEventPublic: "Public",
    addEditEventRequiresApproval: "Requires Approval",
    addEditEventSave: "Save",
    addEditEventSaveFailed: "Save failed. Try again.",
    addEditEventSelectOneCategory: "Select at least one category",
    addEditEventSelectPoster: "Select Poster",
    addEditEventShowAdditionalOptions: "Show additional options",
    addEditEventStartTime: "Start Time",
    addEditEventStartTimeInvalid: "Start Time should be less than End Time",
    addEditEventVirtual: "Virtual",
    addEditEventVisibility: "Visibility",
    addEditEventfacebookConfigurationError: "Facebook integration is not configured properly. Please go to Edit Profile/Facebook tab to reconfigure.",
    administrators: "Administrators",
    browseEventDateTimeOngoing: "Ongoing",
    categoiesModalCancel: "Cancel",
    categoriesModalCategory: "Category",
    categoriesModalDeselectAll: "Deselect All",
    categoriesModalNothingSelected: "Nothing Selected",
    categoriesModalOk: "Ok",
    categoriesModalSelectAll: "Select All",
    categoriesModalSelected: "Selected",
    chatMode: "Chat Mode",
    chatTypeAMessage: "Type a message",
    chats: "Chats",
    countryIsrael: "Israel",
    countryUSA: "USA",
    dashboardAccepted: "Accepted",
    dashboardApproveVolunteers: "Approve Volunteers",
    dashboardApprovedOffers: "Approved Offers",
    dashboardCancelOffer: "Cancel Offer",
    dashboardCancelled: "Cancelled",
    dashboardDeclined: "Declined",
    dashboardDeclinedOffers: "Declined Offers",
    dashboardDuplicateEvent: "Duplicate Event",
    dashboardEditEvent: "Edit Event",
    dashboardGoToEvent: "Go To Event",
    dashboardInviteVolunteers: "Invite Volunteers",
    dashboardOwner: "Owner",
    dashboardPastEvents: "Past Events",
    dashboardPendingApproval: "Your offer is pending approval",
    dashboardRemoveFromList: "Remove from List",
    dashboardTotalEvents: "Total Events Found",
    dashboardWelcome: "Welcome",
    dashboardYouVolunteered: "You volunteered on",
    dateCreated: "Date Created",
    description: "Description",
    distanceServiceKilometer: "kilometer",
    distanceServiceKilometers: "kilometers",
    distanceServiceMile: "mile",
    distanceServiceMiles: "miles",
    editUserPreferencesCountry: "Country",
    editUserPreferencesEditUserPreferences: "Edit User Preferences",
    editUserPreferencesLanguage: "Language",
    editUserPreferencesSave: "Save",
    editVolunteerInfoAddress: "Address",
    editVolunteerInfoBirthDate: "Birth Date",
    editVolunteerInfoChangePassword: "Change Password",
    editVolunteerInfoCharacters: "characters",
    editVolunteerInfoChesedAreas: "Chesed Areas",
    editVolunteerInfoChesedWithin: "Willing to do chesed within",
    editVolunteerInfoConfirmPassword: "Confirm Password",
    editVolunteerInfoConfirmPasswordInvalid: "Confirm password doesn't match",
    editVolunteerInfoContact: "Contact",
    editVolunteerInfoCountry: "Country",
    editVolunteerInfoCredentials: "Credentials",
    editVolunteerInfoDateOfBirthInvalid: "Date of Birth is invalid",
    editVolunteerInfoEditContactInfo: "Edit Contact Info",
    editVolunteerInfoEditPersonalInfo: "Edit Personal Info",
    editVolunteerInfoEditProfessionalInfo: "Edit Professional Info",
    editVolunteerInfoEnterCity: "Enter City",
    editVolunteerInfoEnterNewPassword: "Enter New Password",
    editVolunteerInfoEnterOldPassword: "Enter Old Password",
    editVolunteerInfoEnterState: "Enter State",
    editVolunteerInfoFBLoginPerformed: "You are authenticating with your Facebook account",
    editVolunteerInfoFemale: "Female",
    editVolunteerInfoFirstName: "First Name",
    editVolunteerInfoFullName: "Full Name",
    editVolunteerInfoGender: "Gender",
    editVolunteerInfoInvalidZipCodeError: "Zip Code and City pair is invalid. Please use 'Look Up' to get the correct values.",
    editVolunteerInfoLanguage: "Language",
    editVolunteerInfoLastName: "Last Name",
    editVolunteerInfoLookUp: "Look Up",
    editVolunteerInfoMale: "Male",
    editVolunteerInfoNothingSelected: "Nothing Selected",
    editVolunteerInfoOccupation: "Occupation",
    editVolunteerInfoOccupationDetails: "Occupation Details",
    editVolunteerInfoOldPassword: "Old Password",
    editVolunteerInfoPassword: "Password",
    editVolunteerInfoPasswordMinimumLength: "Passwords must have a minimum length of",
    editVolunteerInfoPersonal: "Personal",
    editVolunteerInfoPhone: "Phone",
    editVolunteerInfoPostalCode: "Postal Code",
    editVolunteerInfoPostalCodeInvalidDigits: "Postal Code must contain digits only.",
    editVolunteerInfoPostalCodeInvalidLength: "Postal Code must be between 5-7 characters long.",
    editVolunteerInfoProfessional: "Professional",
    editVolunteerInfoProfessionalVolunteers: "Professional Volunteers",
    editVolunteerInfoReferenceEmail: "Reference Email",
    editVolunteerInfoReferenceName: "Reference Name",
    editVolunteerInfoSave: "Save",
    editVolunteerInfoSaved: "Saved",
    editVolunteerInfoSelectOneChesedArea: "Please select at least one chesed area",
    editVolunteerInfoSelectRadius: "Please select radius for chesed opportunities.",
    editVolunteerInfoShul: "Main shul where you daven",
    editVolunteerInfoShulAffiliation: "Shul Affiliation",
    editVolunteerInfoSpecialization: "Specialization",
    editVolunteerInfoTextReminders: "Please send me Text reminders of my events at this number",
    editVolunteerInfoUserInfoLoadFailed: "Failed to load user information",
    emailRedirectAlreadyVolunteered: "You have already volunteered for this event.",
    emailRedirectInvalidCode: "Invalid security code.",
    emailRedirectInvalidEvent: "The event is no longer valid.",
    emailRedirectInvalidUser: "Invalid user.",
    emailRedirectLogInToSeeEvents: "Log in to see event on your list.",
    emailRedirectOrganizationAccepted: "is now accepted for your event.",
    emailRedirectOrganizationAlreadyAccepted: "has been already accepted for your event.",
    emailRedirectOrganizationAlreadyDeclined: "has been already declined for your event.",
    emailRedirectOrganizationDeclined: "is now declined for your event.",
    emailRedirectOrganizationEventStaffed: "Event is fully staffed.",
    emailRedirectOrganizationInvalidCode: "Invalid security code.",
    emailRedirectOrganizationNotInterestedToAccept: "is no longer interested in the event and has not been added to your volunteer list.",
    emailRedirectOrganizationNotInterestedToDecline: "is no longer interested in the event.",
    emailRedirectOrganizationOfferAlreadyDeclined: "You have already declined this offer.",
    emailRedirectOrganizationRequestInvalid: "This volunteer request is no longer valid.",
    emailRedirectOrganizationUseDashboard: "You have already accepted this offer. Please use dashboard to decline it.",
    emailRedirectOrganizationVolunteer: "Volunteer",
    emailRedirectUseCredentials: "Use proper credentials to see events on the list.",
    emailRedirectVolunteeredForFilled: "You have volunteered successfully, but this event is already filled. We will contact you if additional help is required. Thank you",
    emailRedirectVolunteeredSuccessfully: "You volunteered successfully.",
    eventChatMode: "Chat Mode",
    eventDetailActive: "Active",
    eventDetailClosed: "Closed",
    eventDetailEditEvent: "Edit Event",
    eventDetailInactive: "Inactive",
    eventDetailStatus: "Status",
    eventDetailVolunteers: "Volunteers",
    eventDetailsChesedChat: "Chesed Chat",
    eventDetailsChesedDetails: "Chesed Details",
    eventDetailsOrganizationAccept: "Accept",
    eventDetailsOrganizationCancelEvent: "Cancel Event",
    eventDetailsOrganizationClose: "close",
    eventDetailsOrganizationConfirmed: "Confirmed",
    eventDetailsOrganizationContactInfo: "Contact Info",
    eventDetailsOrganizationDeactivateEvent: "Deactivate Event",
    eventDetailsOrganizationDecline: "Decline",
    eventDetailsOrganizationDeclined: "Declined",
    eventDetailsOrganizationEmailToVolunteerSent: "Email to volunteer was successfully sent",
    eventDetailsOrganizationEmailsToVolunteersSent: "Emails to volunteers were successfully sent",
    eventDetailsOrganizationFemale: "Female",
    eventDetailsOrganizationInterested: "Interested",
    eventDetailsOrganizationMale: "Male",
    eventDetailsOrganizationNameAgeGender: "Name/Age/Gender",
    eventDetailsOrganizationNoMoreVacancies: "No more vacancies to confirm...",
    eventDetailsOrganizationOngoing: "Ongoing",
    eventDetailsOrganizationOpen: "open",
    eventDetailsOrganizationReactivateEvent: "Reactivate Event",
    eventDetailsOrganizationSendSuccess: "Send success",
    eventDetailsOrganizationStaffing: "Staffing:",
    eventDetailsOrganizationStatus: "Status",
    eventJoinCriteria: "Join Criteria",
    eventStatusCancelled: "Cancelled",
    eventStatusClosed: "Closed",
    eventStatusDeactivated: "Deactivated",
    eventStatusOpen: "Open",
    eventVisibility: "Visibility",
    eventsDisplayNumberDisplaying: "Displaying",
    eventsDisplayNumberEvents: "events",
    eventsDisplayNumberOf: "of",
    eventsPosterInfo: "Poster Information",
    eventsPosterTypeErrorMessage: "Please select events poster type",
    eventsPosterTypeText: "Events Poster Type",
    failedOpenDistanceDropdownMessage: "Please select a zip code to enable a distance search",
    findVolunteerAlreadySent: "Already Sent",
    findVolunteerCategory: "Category",
    findVolunteerCityZipPhone: "City/Zip/Phone",
    findVolunteerEmail: "Email",
    findVolunteerEventLoadFailed: "Failed to load post",
    findVolunteerFemale: "Female",
    findVolunteerFindingVolunteers: "Finding Volunteers for Post",
    findVolunteerHide: "Hide",
    findVolunteerIncludePastConfirmed: "Only Include Past Confirmed Volunteers",
    findVolunteerInvitation: "Invitation",
    findVolunteerMale: "Male",
    findVolunteerName: "Name",
    findVolunteerNameAgeGender: "Name/Age/Gender",
    findVolunteerOngoing: "Ongoing",
    findVolunteerPeople: "people",
    findVolunteerReference: "Reference",
    findVolunteerResults: "Results",
    findVolunteerSelected: "Selected",
    findVolunteerSend: "Send",
    findVolunteerSendInvitations: "Send Invitations",
    findVolunteerSentTo: "Sent to",
    findVolunteerShowHidden: "Show Hidden",
    findVolunteerShowingFirst: "Showing First",
    findVolunteerStatus: "Status",
    findVolunteerTotalVolunteers: "Total Volunteers Found",
    findVolunteerUser: "User",
    findVolunteerUserInfoUpdateFailed: "Failed to update user info",
    findVolunteerVolunteersSelected: "All volunteers selected below have already been contacted",
    indexBrowseOpportunities: "Browse Opportunities",
    indexContact: "Contact",
    indexContinue: "Continue",
    indexDashboard: "Chesed Dashboard",
    indexDistance: "Distance",
    indexEditProfile: "(Edit Profile)",
    indexEditProfileMobile: "Edit Profile",
    indexEventView: "View",
    indexFilters: "Filters",
    indexFiltersSelectCategory: "Select",
    indexFindChesedOpportunity: "Find a chesed opportunity from the list below and volunteer today",
    indexFindNear: "Postal Code",
    indexHello: "Hello",
    indexHome: "Home",
    indexJoinVolunteersFirst: "Join Volunteers in your Community",
    indexJoinVolunteersSecond: "Sign up today",
    indexJustOneChesed: "JustOneChesed",
    indexLogIn: "Log in",
    indexLogOut: "Log out",
    indexManageOrganization: "Manage Organization",
    indexManageOrganizations: "Manage Organizations",
    indexManageVolunteers: "Manage Volunteers",
    indexNothingSelected: "Nothing Selected",
    indexOpportunities: "JustOneChesed Opportunities",
    indexOrganizationDirectory: "Organization Directory",
    indexSearch: "Search for",
    indexSearchForServices: "Search For Services",
    indexSearchProfessionals: "Search Professionals",
    indexSearchReset: "Reset",
    indexSearchTerm: "Search Terms",
    indexSignUp: "Sign up",
    indexTotalEvents: "Total Events Found",
    indexTotalRecords: "Total Records Found",
    indexVolunteer: "Volunteer",
    indexVolunteered: "Volunteered. See status in your dashboard",
    invalidZipCode: "Please enter a valid postal code",
    joinCriteria: "Join Criteria",
    languageEnglish: "English",
    languageEnglishRegister: "English",
    languageHebrew: "עברית",
    languageHebrewRegister: "Hebrew",
    languageSelectorEnglish: "English",
    leftMenuChesedFeed: "Chesed Feed",
    leftMenuPrivateChats: "Private Chats",
    loginCaptchaIncorrect: "Captcha Incorrect",
    loginCreateAccount: "Create account",
    loginEmail: "E-mail",
    loginEmailConfirmed: "Your email address has been confirmed. Please log in to use the system.",
    loginEnterPassword: "Enter Password",
    loginEnterUserName: "Enter Username",
    loginForgotPassword: "Forgot password",
    loginLogin: "Login",
    loginLoginFailed: "Login failed. Try again.",
    loginPassword: "Password",
    loginSecurityCheck: "Security Check",
    loginSignIn: "Sign In",
    loginSuccessfullyVolunteered: "Successfully Volunteered",
    loginTitle: "JustOneChesed Sign in",
    manageOrganizationsCityZipPhone: "City/Zip/Phone",
    manageOrganizationsEdit: "Edit",
    manageOrganizationsEditOrganizations: "Edit Organizations Info",
    manageOrganizationsEmail: "Email",
    manageOrganizationsOrganizationName: "Organization Name",
    manageOrganizationsSearch: "Search",
    manageOrganizationsSuspend: "Suspend",
    manageOrganizationsTotalOrganizations: "Total Organizations Found",
    manageOrganizationsWebsite: "Website",
    manageVolunteersCityZipPhone: "City/Zip/Phone",
    manageVolunteersEdit: "Edit",
    manageVolunteersEditVolunteers: "Edit Volunteers Info",
    manageVolunteersEmail: "Email",
    manageVolunteersNameAgeGender: "Name/Age/Gender",
    manageVolunteersSearch: "Search",
    manageVolunteersSuspend: "Suspend",
    manageVolunteersTotalVolunteers: "Total Volunteers Found",
    memberAction: "Edit",
    memberAllEvents: "All Events",
    memberAllEventsIncluding: "All events (including cancelled)",
    memberAllPosters: "All Posters",
    memberApply: "Apply",
    memberCategory: "Category",
    memberConfirmed: "Confirmed",
    memberCreateNewEvent: "Create Post",
    memberDueDate: "Due Date",
    memberDuplicate: "Duplicate",
    memberFindVolunteers: "Find Volunteers",
    memberFullyStaffed: "Fully Staffed",
    memberInterested: "Interested",
    memberInternalNotes: "Internal Notes",
    memberOfferedByYou: "Offered By You",
    memberOngoing: "Ongoing",
    memberRemainingNeeded: "Remaining Needed",
    memberSearchInternal: "Search Internal Notes",
    memberSelected: "Selected",
    memberStatus: "Status",
    memberTitle: "Title",
    memberTotalEvents: "Total Posts Found",
    memberVolunteersNeeded: "Volunteers Needed",
    memberYourEvents: "Your Posts",
    members: "Members",
    multipleSelectModalCancel: "Cancel",
    multipleSelectModalClearAll: "Clear All",
    multipleSelectModalOk: "OK",
    myProfile: "My Profile",
    myProfileAddress: "Address",
    myProfileBirthdate: "Birth Date",
    myProfileDetails: "Detail",
    myProfileEmail: "Email",
    myProfileEventsVolunteered: "Events Volunteered",
    myProfileFemale: "Female",
    myProfileFirstName: "First Name",
    myProfileGender: "Gender",
    myProfileLastName: "Last Name",
    myProfileMale: "Male",
    myProfileName: "Name",
    myProfileNoOrganizations: "No organizations",
    myProfileOrganizationMembership: "Organization Membership",
    myProfileOrganizations: "Organizations",
    myProfilePersonalDetails: "Personal Details",
    myProfilePhoneNumber: "Phone No.",
    myProfileSaveChanges: "Save changes",
    myProfileTelephone: "Phone",
    myProfileTotalChats: "Total Chats",
    needToChangePassword: "You need to change your password",
    noEvents: "No events",
    noText: "No",
    opportunity: "Opportunity",
    organizationManagementAddAdministrator: "Add Administrator",
    organizationManagementAddMember: "Add Member",
    organizationManagementAddress: "Address",
    organizationManagementAdministrators: "Administrators",
    organizationManagementAge: "Age",
    organizationManagementEmail: "Email",
    organizationManagementFirstName: "First Name",
    organizationManagementIsActive: "Is Active",
    organizationManagementIsApproved: "Is Approved",
    organizationManagementLastName: "Last Name",
    organizationManagementManageOrganization: "Manage Organization",
    organizationManagementMembers: "Members",
    organizationManagementMissionStatement: "Mission Statement",
    organizationManagementMyOrganization: "My Organization",
    organizationManagementNoAdministrators: "No administrators",
    organizationManagementNoMembers: "No members",
    organizationManagementOpportunity: "Opportunity",
    organizationManagementOrganizationAdministrators: "Organization Administrators",
    organizationManagementOrganizationDetails: "OrganizationDetails",
    organizationManagementOrganizationMembers: "Organization Members",
    organizationManagementOrganizationName: "Organization Name",
    organizationManagementOrganizationalDirectory: "Organizational Directory",
    organizationManagementPhoneNo: "Phone No.",
    organizationManagementPhoneNumber: "Phone Number",
    organizationManagementSelectOpportunity: "Select opportunity to see volunteers",
    organizationManagementUpdateOrganization: "Update Organization",
    organizationManagementWebsite: "Website",
    pagingNext: "Next",
    pagingPrevious: "Previous",
    profilePopDownLogout: "Logout",
    profileSavedMsg: "Your Chesed Area changes were saved.",
    profileTabChesedAreas: "Chesed Areas",
    profileTabPersonalInformation: "Personal Information",
    readMoreReadMore: "Read more",
    registerChesedAreas: "Chesed Areas",
    registerIndividual: "Individual",
    registerIndividualAccontInfo: "Personal Account Information",
    registerOrganization: "Organization",
    registerOrganizationAdd: "Add",
    registerOrganizationAddress: "Address",
    registerOrganizationAddressOptional: "Address (optional)",
    registerOrganizationAllowToPostEvents: "Allow Just Once Chesed to post events you create to Facebook pages your manage",
    registerOrganizationAlreadyHaveAnAccount: "Already have an account?",
    registerOrganizationBack: "Back",
    registerOrganizationChangePassword: "I want to change password",
    registerOrganizationCharacters: "characters",
    registerOrganizationClear: "Clear",
    registerOrganizationCompletedMessage: "Your Organization was Successfully Registered and is now awaiting administrator approval. If you have any questions please contact us at",
    registerOrganizationCompletedRegistrationCompleted: "Registration Completed",
    registerOrganizationConfirmPassword: "Confirm Password",
    registerOrganizationConfirmPasswordInvalid: "Confirm password doesn't match.",
    registerOrganizationContactDirectory: "Contact Directory",
    registerOrganizationCreatePassword: "Create Your Password",
    registerOrganizationDepartment: "Department",
    registerOrganizationDescription: "Description",
    registerOrganizationDetailsMinLengthInvalid: "Description Should be Minimum 20 Characters Length",
    registerOrganizationDisable: "Disable",
    registerOrganizationDone: "Done",
    registerOrganizationEditOrganization: "Edit Organization",
    registerOrganizationEmail: "Email",
    registerOrganizationEnable: "Enable",
    registerOrganizationEnterAddress: "Enter Organization Address",
    registerOrganizationEnterCity: "Enter City",
    registerOrganizationEnterDetails: "Enter Details",
    registerOrganizationEnterEmail: "Enter Your Login Email Address",
    registerOrganizationEnterName: "Enter Organization Name",
    registerOrganizationEnterNewPassword: "Enter New Password",
    registerOrganizationEnterOldPassword: "Enter Old Password",
    registerOrganizationEnterPhone: "Enter Organization Phone",
    registerOrganizationEnterState: "Enter State",
    registerOrganizationEnterWebsite: "Enter Organization Website Address",
    registerOrganizationFacebookPages: "Facebook Pages",
    registerOrganizationFax: "Fax",
    registerOrganizationGemachItems: "What Items Do You Have in Your Gemach? (comma-separated list)",
    registerOrganizationGmach: "Gmach",
    registerOrganizationGrantSecurityMessage: "We will neve post without your permission",
    registerOrganizationHaveGemach: "We have/are a Gemach",
    registerOrganizationImageFormats: "Only jpg and png are allowed.",
    registerOrganizationImageSize: "File size should be less than 5mb",
    registerOrganizationIntegrationDisableFailed: "Failed to disable Integration. Try again.",
    registerOrganizationIntegrationEnableFailed: "Failed to enable Integration. Try again.",
    registerOrganizationInvalidEmailFormat: "Email format is incorrect",
    registerOrganizationInvalidOwner: "Only organization owner can enable integration.",
    registerOrganizationInvalidZipCodeError: "Zip Code and City pair is invalid. Please use 'Look Up' to get the correct values.",
    registerOrganizationLogoAdded: "Logo was successfully added",
    registerOrganizationLogoUploadFailed: "Logo upload failed",
    registerOrganizationLookUp: "Look Up",
    registerOrganizationMissionStatement: "Description - Mission Statement",
    registerOrganizationName: "Name",
    registerOrganizationNextStep: "Next Step",
    registerOrganizationNothingSelected: "Nothing Selected",
    registerOrganizationOldPassword: "Old Password",
    registerOrganizationOnceChanged: "Once changed, you will need to relogin under new email.",
    registerOrganizationOneContactRequired: "Minimum one contact required.",
    registerOrganizationOrganization: "Organization",
    registerOrganizationOrganizationCountry: "Organization Country",
    registerOrganizationOrganizationInfo: "Organization Info",
    registerOrganizationOrganizationLanguage: "Organization Language",
    registerOrganizationOrganizationLoadFailed: "Failed to load current organization.",
    registerOrganizationOrganizationName: "Organization Name",
    registerOrganizationOrganizationRegisterType: "Organization Register Type",
    registerOrganizationOrganizationType: "Organization Type",
    registerOrganizationPagesUpdateFailed: "Failed to update pages. Try again.",
    registerOrganizationPassword: "Password",
    registerOrganizationPasswordMinimumLength: "Passwords must have a minimum length of",
    registerOrganizationPhone: "Phone",
    registerOrganizationPhoneNumber: "Phone Number",
    registerOrganizationPostalCode: "Postal Code",
    registerOrganizationPostalCodeInvalidDigits: "Postal Code must contain digits only.",
    registerOrganizationPostalCodeInvalidLength: "Postal Code must be between 5-7 characters long.",
    registerOrganizationQuestion: "Are you registering an Organization?",
    registerOrganizationRegisterOrganization: "Register Organization",
    registerOrganizationRegistrationFailed: "Registration failed. Try again.",
    registerOrganizationRemoveLogo: "I want to remove Logo",
    registerOrganizationSave: "Save",
    registerOrganizationSaveFailed: "Save failed. Try again.",
    registerOrganizationSaved: "Saved",
    registerOrganizationSchool: "School",
    registerOrganizationSelectLogo: "Select File for Your Logo...",
    registerOrganizationSelectYourCountry: "Select Your Country",
    registerOrganizationSelectYourLanguage: "Select Your Language",
    registerOrganizationSelected: "Selected",
    registerOrganizationServiceName: "Name of Service",
    registerOrganizationServices: "Services You Offer",
    registerOrganizationServicesDescription: "Enter the services you offer in the spaces below along with a short description of each one. This will help those in need to easily locate your organization and find the assistance they require.",
    registerOrganizationServicesProvided: "Services Provided",
    registerOrganizationShul: "Shul",
    registerOrganizationSkip: "Skip",
    registerOrganizationSpecifyPages: "Specify the pages you want your events to be posted to",
    registerOrganizationSuccessfullyUpdated: "Successfully updated.",
    registerOrganizationUploadLogo: "Upload Organization Logo",
    registerOrganizationWebsiteFormatInvalid: "Website format is incorrect",
    registerOrganizationWebsiteMaxLengthInvalid: "Website Should be Maximum 60 Characters Length",
    registerOrganizationWelcomeToTitle: "Welcome to Just One Chesed",
    registerOrganizationWithEmail: "Continue with my email",
    registerOrganizationWithExistingAccount: "I already have an account with my email",
    registerOrganizationWithFacebook: "Continue with Facebook",
    registerOrganizationYourSite: "www.yoursite.com",
    registerQuestion: "New to JustOneChesed?",
    registerRequiredFieldsLegend: "Required fields / sections",
    registerSignUpOrganization: "Organizations are able to post their opportunities to the board and search for a targeted list of volunteers to staff your events",
    registerSignUpVolunteer: "Sign up as a volunteer to receive offers from organizations and to volunteer for the events you choose",
    registerVolunteer: "Volunteer",
    registerVolunteerAlreadyHaveAnAccount: "Already have an account?",
    registerVolunteerAsIndividual: "Register as an individual",
    registerVolunteerAsOrganization: "Register as an organization",
    registerVolunteerBack: "Back",
    registerVolunteerCategories: "Categories",
    registerVolunteerCharacters: "characters",
    registerVolunteerChesedWithin: "Willing to do chesed within",
    registerVolunteerChooseGender: "Choose Your Gender",
    registerVolunteerCity: "City",
    registerVolunteerConfirmPassword: "Confirm Password",
    registerVolunteerConfirmPasswordInvalid: "Confirm password doesn't match",
    registerVolunteerCreatePassword: "Create Your Password",
    registerVolunteerDatabaseOfProfessionals: "We are building a powerful database of professionals. Let us know how you would like to help out within your field",
    registerVolunteerDateOfBirthInvalid: "Date of Birth is invalid",
    registerVolunteerDone: "Done",
    registerVolunteerEmail: "Email",
    registerVolunteerEnterBirthDate: "Enter Your Birth Date",
    registerVolunteerEnterEmail: "Enter Your Email",
    registerVolunteerEnterFullName: "Enter Your Full Name",
    registerVolunteerEnterLocation: "Enter Your Location",
    registerVolunteerEnterPhone: "Enter Your Phone",
    registerVolunteerFemale: "Female",
    registerVolunteerFirstName: "First Name",
    registerVolunteerGrantSecurityMessage: "We will never post without your permission",
    registerVolunteerInvalidEmailFormat: "Email format is incorrect",
    registerVolunteerInvalidZipCodeError: "Zip Code and City pair is invalid. Please use 'Look Up' to get the correct values.",
    registerVolunteerLastName: "Last Name",
    registerVolunteerLoginToJOC: "Login to Just One Chesed to view you chesed dashboard and volunteer for events",
    registerVolunteerLookUp: "Look Up",
    registerVolunteerMale: "Male",
    registerVolunteerNextStep: "Next Step",
    registerVolunteerNothingSelected: "Nothing Selected",
    registerVolunteerOccupation: "Occupation",
    registerVolunteerOccupationDetails: "Occupation Details",
    registerVolunteerPassword: "Password",
    registerVolunteerPasswordMinimumLength: "Passwords must have a minimum length of",
    registerVolunteerPostalCode: "Postal Code",
    registerVolunteerPostalCodeInvalidDigits: "Postal Code must contain digits only.",
    registerVolunteerPostalCodeInvalidLength: "Postal Code must be between 5-7 characters long.",
    registerVolunteerProfessionalVolunteers: "Professional Volunteers",
    registerVolunteerQuestion: "Creating an account for a volunteer?",
    registerVolunteerRegistration: "Registration Successful",
    registerVolunteerRegistrationCompleted: "Welcome to JustOneChesed!",
    registerVolunteerRegistrationFailed: "Registration failed. Try again.",
    registerVolunteerRequiredFieldsMustBeFilled: "All required fields must be filled",
    registerVolunteerSelect: "Select",
    registerVolunteerSelectChesedAreas: "Select Chesed Areas",
    registerVolunteerSelectChesedAreasFullText: "Please select the Chesed areas that you are interested in. JustOneChesed will use your selections to send you notifications about new opportunities. If you do not wish to receive notifications at this time then simply click done.",
    registerVolunteerSelectOneChesedArea: "Please select at least one chesed area",
    registerVolunteerSelectRadius: "Please select radius for chesed opportunities.",
    registerVolunteerSelectYourCountry: "Select Your Country",
    registerVolunteerSelectYourLanguage: "Select Your Language",
    registerVolunteerSelected: "Selected",
    registerVolunteerSpecialization: "Specialization",
    registerVolunteerStep1: "Step 1",
    registerVolunteerStep2: "Step 2",
    registerVolunteerStep3: "Step 3",
    registerVolunteerStep4: "Step 4",
    registerVolunteerTextReminders: "Please send me Text reminders of my events at this number",
    registerVolunteerUsedEmail: "Email is already used",
    registerVolunteerVolunteer: "Volunteer",
    registerVolunteerWelcomeToTitle: "Welcome to Just One Chesed",
    registerVolunteerWithEmail: "Continue with my email",
    registerVolunteerWithFacebook: "Continue with Facebook",
    searchForServicesCity: "Enter City",
    searchForServicesDistance: "Distance",
    searchForServicesFindNear: "Postal Code",
    searchForServicesGemachItems: "Gemach Items",
    searchForServicesNothingSelected: "Nothing Selected",
    searchForServicesOR: "or",
    searchForServicesOnlyGemach: "Only Search Gemach",
    searchForServicesOrganizationType: "Organization Type",
    searchForServicesSearch: "Search",
    searchForServicesSearchForOrganizations: "Search for organizations offering these services or gemach items...",
    searchForServicesSelectOrganizationType: "Select Type",
    searchForServicesState: "Enter State",
    searchForServicesTotalOrganizations: "Total Organizations Found",
    searchForServicesTypeTitle: "Type",
    searchForServicesWebsite: "Website",
    searchProfessionalsCityZipPhone: "City / Zip / Phone",
    searchProfessionalsEmail: "Email",
    searchProfessionalsFindNear: "Postal Code",
    searchProfessionalsNameAgeGender: "Name / Age / Gender",
    searchProfessionalsNameEmail: "Name / Email",
    searchProfessionalsNothingSelected: "Nothing Selected",
    searchProfessionalsOccupation: "Occupation",
    searchProfessionalsReference: "Reference",
    searchProfessionalsResults: "Results",
    searchProfessionalsSearch: "Search",
    searchProfessionalsSearchProfessionals: "Search Professionals",
    searchProfessionalsShowingFirst: "Showing First",
    searchProfessionalsSpecialization: "Specialization",
    searchProfessionalsState: "Enter State",
    searchProfessionalsTotalProfessionals: "Total Professionals Found:",
    selectOpportunityToSeeVolunteers: "Select Opportunity To See Volunteers",
    signinVolunteerWithEmail: "Sign in with email",
    signinVolunteerWithFacebook: "Sign in with Facebook",
    subCategoriesModalCancel: "Cancel",
    subCategoriesModalClearAll: "Clear All",
    subCategoriesModalOk: "OK",
    title: "Title",
    topMenuVisitMyProfile: "Visit my profile",
    updateOrganization: "Update Organization",
    userDetails: "User Details",
    volunteerCategoryCenterText1: "Select",
    volunteerCategoryCenterText2: "Volunteer",
    volunteerCategoryCenterText3: "Categories",
    volunteerMsgThankyou: "Thank you for volunteering for {0}.",
    volunteerMsgWaitForApproval: "This opportunity requires a response from the organizer. You should hear from them shortly.",
    yesText: "Yes",
    zipCodeLookUpInvalidBuildingNumber: "Invalid building number format.",
    zipCodeLookUpModalApply: "Apply",
    zipCodeLookUpModalBuildingNumber: "Select Building Number",
    zipCodeLookUpModalCancel: "Cancel",
    zipCodeLookUpModalCity: "Select City",
    zipCodeLookUpModalClearAll: "Clear All",
    zipCodeLookUpModalNoBuildingMatchInfo: "If there is no exact match, please, select the closest building",
    zipCodeLookUpModalStartTyping: "Start typing...",
    zipCodeLookUpModalStreet: "Select Street",
    zipCodeLookUpModalTitle: "Postal Code Look Up",
    zipCodeLookUpModalZipCode: "Postal Code",
    zipCodeLookUpNoResults: "No Results",
    eventDetails: 'Chesed Details',
    newOpportunityIDF: 'IDF',
    newOpportunityFinancing: 'FINANCING',
    newOpportunityMothersHelper: 'MOTHERS HELPER',
    newOpportunityFoodCooking: 'FOOD / COOKING',
    newOpportunityEM: 'ENTERTAIMENT / MUSIC',
    newOpportunityMediaTech: 'MEDIA / TECH',
    newOpportunityHachanasOrchim: 'HACHANAS ORCHIM',
    newOpportunityTefillah: 'TEFILLAH',
    newOpportunityTorah: 'TORAH',
    newOpportunityDriving: 'DRIVING',
    newOpportunityTutoringLessons: 'TUTORING / LESSONS',
    newOpportunityMentoring: 'MENTORING',
    newOpportunityManPower: 'MAN POWER',
    newOpportunityCelebrationsEvents: 'CELEBRATIONS / EVENTS',
    newOpportunityHolidayHelp: 'HOLIDAY HELP',
    newOpportunityBikurCholim: 'BIKUR CHOLIM',
    newOpportunitySeniorHelp: 'SENIOR HELP',
    newOpportunityNewOlim: 'NEW OLIM',
    settingLanguages: "Language",
    myProfileSelectBirthDate: "Select Birthdate",
    menuItemSettings: "Settings"
  },
  he: {
    addEditEventAddress: "כתובת (לא חובה)",
    addEditEventAdminOnly: "מנהל בלבד",
    addEditEventAnyoneCanJoin: "כל אחד יכול להצטרף",
    addEditEventBrowse: "עיון",
    addEditEventCancel: "ביטול",
    addEditEventCategory: "קטגוריה",
    addEditEventChatModes: "מצבי צ 'אט",
    addEditEventChooseCategory: "בחר/י קטגוריה",
    addEditEventChooseDate: "בחר/י תאריך",
    addEditEventCreateEvent: "צור הזדמנות",
    addEditEventCreateNewEvent: "צור פוסט חדש",
    addEditEventCreateOpportunity: "יצירת הזדמנות",
    addEditEventDescriptionIsRequired: "התיאור נדרש",
    addEditEventDescriptionTooShort: "תיאור האירוע יהיה לכל הפחות  30 תווים",
    addEditEventEditEvent: "ערוך פוסט",
    addEditEventEditOpportunity: "ערוך הזדמנות",
    addEditEventEndTime: "שעת סיום",
    addEditEventEnterCity: "הזן עיר",
    addEditEventEnterDescription: "הזן תיאור",
    addEditEventEnterEventAddress: "הכנס כתובת",
    addEditEventEnterState: "מדינה",
    addEditEventEventDateInvalid: "תאריך הפוסט אינו חוקי",
    addEditEventEventDateInvalidPast: "תאריך הפוסט לא יכול להיות מוקדם יותר מהיום",
    addEditEventEventDescription: "תאור תיאור",
    addEditEventEventSaved: "הפוסט נשמר בהצלחה",
    addEditEventEventTitle: "כותרת פוסט",
    addEditEventHideAdditionalOptions: "הסתר אפשרויות נוספות",
    addEditEventInternalNotes: "הערות פנימיות",
    addEditEventInvalidZipCodeError: " מיקוד ושם עיר אינם תואמים. נא השתמש ב'חיפוש' כדי לקבל נתונים נכונים.",
    addEditEventJoinCriteria: "קריטריונים להצטרפות",
    addEditEventLocal: "מקומי",
    addEditEventLocation: "מקום",
    addEditEventLookUp: "חפש",
    addEditEventMembersOnly: "לחברים בלבד",
    addEditEventNameIsRequired: "נדרש שם",
    addEditEventOngoingEvent: "פוסט מתמשך",
    addEditEventOpenToAll: "פתוח לכל",
    addEditEventOpenToMembers: "פתוח לחברי",
    addEditEventOpenToVolunteers: "פתוח למתנדבים",
    addEditEventPeopleNeeded: "מספר האנשים הדרושים",
    addEditEventPostToFacebook: "להעלות לפייסבוק",
    addEditEventPostToFacebookExplanation: " העלה לעמוד הפייסבוק. אנא גש ללשונית, ערוך פרופיל, בכדי להפעיל דף זה.",
    addEditEventPostalCode: "מיקוד",
    addEditEventPostalCodeInvalidLength: "על אורך המיקוד להיות בין 5-7 תווים",
    addEditEventPoster: "מפרסם",
    addEditEventPrivate: "פרטי",
    addEditEventPublic: "גלוי",
    addEditEventRequiresApproval: "דורש אישור",
    addEditEventSave: "שמור",
    addEditEventSaveFailed: "השמירה נכשלה. נסה שוב.",
    addEditEventSelectOneCategory: "בחר לפחות קטגוריה אחת",
    addEditEventSelectPoster: "בחר מפרסם",
    addEditEventShowAdditionalOptions: "הצג אפשרויות נוספות",
    addEditEventStartTime: "שעת ההתחלה",
    addEditEventStartTimeInvalid: "שעת התחלה צריכה להיות לפני שעת הסיום",
    addEditEventVirtual: "וירטואלי",
    addEditEventVisibility: "פרטיות",
    addEditEventfacebookConfigurationError: "העלאה לדף הפייסבוק לא נעשה כראוי. אנא גש ללשונית 'ערוך פרופיל' והגדר מחדש.",
    administrators: "מנהלים",
    browseEventDateTimeOngoing: "מתמשך",
    categoiesModalCancel: "בטל",
    categoriesModalCategory: "קטגוריה",
    categoriesModalDeselectAll: "הסר סימון מהכל",
    categoriesModalNothingSelected: "לא נבחר שום דבר ",
    categoriesModalOk: "אוקיי/בסדר",
    categoriesModalSelectAll: "בחר הכל",
    categoriesModalSelected: "נבחר",
    chatMode: "מצב צ'אט",
    chatTypeAMessage: "הקלד הודעה",
    chats: "צ'אטים",
    countryIsrael: "ישראל",
    countryUSA: "ארה''ב",
    dashboardAccepted: "התקבל",
    dashboardApproveVolunteers: "אישור מתנדבים",
    dashboardApprovedOffers: "הצעות מאושרות",
    dashboardCancelOffer: "בטל את ההצעה",
    dashboardCancelled: "בוטל",
    dashboardDeclined: "נדחה",
    dashboardDeclinedOffers: "הצעות שנדחו",
    dashboardDuplicateEvent: "שכפל את האירוע",
    dashboardEditEvent: "הגדרות אירוע",
    dashboardGoToEvent: "עבור לאירוע",
    dashboardInviteVolunteers: "זימון מתנדבים",
    dashboardOwner: "Owner",
    dashboardPastEvents: "אירועים בעבר",
    dashboardPendingApproval: "הצעתך ממתינה לאישור",
    dashboardRemoveFromList: "הסר מהרשימה",
    dashboardTotalEvents: 'נמצאו סה"כ אירועים',
    dashboardWelcome: "ברוך הבא",
    dashboardYouVolunteered: "התנדבת ב-",
    dateCreated: "תאריך יצירה",
    description: "תיאור",
    distanceServiceKilometer: 'ק"מ',
    distanceServiceKilometers: 'ק"מ',
    distanceServiceMile: "mile",
    distanceServiceMiles: "miles",
    duplicateEvent: "שכפל את האירוע",
    editEvent: "שנה את האירוע",
    editUserPreferencesCountry: "מדינה",
    editUserPreferencesEditUserPreferences: "עריכת העדפות משתמש",
    editUserPreferencesLanguage: "שפה",
    editUserPreferencesSave: "שמור",
    editVolunteerInfoAddress: "כתובת",
    editVolunteerInfoBirthDate: "תאריך לידה",
    editVolunteerInfoChangePassword: "שינוי סיסמה",
    editVolunteerInfoCharacters: "תווים",
    editVolunteerInfoChesedAreas: "תחומי חסד",
    editVolunteerInfoChesedWithin: "מוכן לעשות חסד ב-",
    editVolunteerInfoConfirmPassword: "אשר סיסמה",
    editVolunteerInfoConfirmPasswordInvalid: "הסיסמאות אינן תואמות",
    editVolunteerInfoContact: "צור קשר",
    editVolunteerInfoCountry: "מדינה",
    editVolunteerInfoCredentials: "אישורים",
    editVolunteerInfoDateOfBirthInvalid: "תאריך הלידה שגוי",
    editVolunteerInfoEditContactInfo: "ערוך מידע ליצירת קשר",
    editVolunteerInfoEditPersonalInfo: "ערוך פרטים אישיים",
    editVolunteerInfoEditProfessionalInfo: "ערוך מידע מקצועי",
    editVolunteerInfoEnterCity: "הזן עיר",
    editVolunteerInfoEnterNewPassword: "הזן סיסמה החדשה",
    editVolunteerInfoEnterOldPassword: "הזן סיסמה הישנה",
    editVolunteerInfoEnterState: "NA",
    editVolunteerInfoFBLoginPerformed: "מחובר עם פייסבוק",
    editVolunteerInfoFemale: "נקבה",
    editVolunteerInfoFirstName: "שם פרטי",
    editVolunteerInfoFullName: "שם מלא",
    editVolunteerInfoGender: "מגדר",
    editVolunteerInfoInvalidZipCodeError: "מיקוד ושם עיר אינם תואמים. נא השתמש ב'חיפוש' כדי לקבל נתונים נכונים.",
    editVolunteerInfoLanguage: "שפה",
    editVolunteerInfoLastName: "שם משפחה",
    editVolunteerInfoLookUp: "חפש",
    editVolunteerInfoMale: "זכר",
    editVolunteerInfoNothingSelected: "לא נבחר שום דבר ",
    editVolunteerInfoOccupation: "מקצוע",
    editVolunteerInfoOccupationDetails: "פרטי מקצוע",
    editVolunteerInfoOldPassword: "סיסמה ישנה",
    editVolunteerInfoPassword: "סיסמה",
    editVolunteerInfoPasswordMinimumLength: "אורך הסיסמה חייב להיות לפחות..",
    editVolunteerInfoPersonal: "אישי",
    editVolunteerInfoPhone: "טלפון",
    editVolunteerInfoPostalCode: "מיקוד",
    editVolunteerInfoPostalCodeInvalidDigits: "המיקוד יכול להכיל ספרות בלבד",
    editVolunteerInfoPostalCodeInvalidLength: "המיקוד חייב לכלול בין 5-7 תווים.",
    editVolunteerInfoProfessional: "מקצועי",
    editVolunteerInfoProfessionalVolunteers: "מתנדבים מקצועיים",
    editVolunteerInfoReferenceEmail: 'דוא"ל המפנה',
    editVolunteerInfoReferenceName: "שם המפנה",
    editVolunteerInfoSave: "שמור",
    editVolunteerInfoSaved: "שמור",
    editVolunteerInfoSelectOneChesedArea: "אנא בחר תחום חסד אחד לפחות",
    editVolunteerInfoSelectRadius: "אנא בחר תחום חסד בו תוכל להתנדב",
    editVolunteerInfoShul: 'ביהכנ"ס שבו אתה מתפלל בעיקר',
    editVolunteerInfoShulAffiliation: 'השתייכות לביהכנ"ס',
    editVolunteerInfoSpecialization: "התמחות",
    editVolunteerInfoTextReminders: "נא לשלוח לי SMS עם תזכורות לגבי האירועים שלי למספר זה",
    editVolunteerInfoUserInfoLoadFailed: "טעינת מידע של המשתמש נכשל",
    emailRedirectAlreadyVolunteered: "כבר התנדבת לאירוע זה",
    emailRedirectInvalidCode: "קוד אבטחה שגוי",
    emailRedirectInvalidEvent: "האירוע אינו בתוקף",
    emailRedirectInvalidUser: "שם משתמש לא חוקי",
    emailRedirectLogInToSeeEvents: "התחבר כדי לצפות באירוע ברשימה שלך.",
    emailRedirectOrganizationAccepted: "המתנדב התקבל לאירוע שלך",
    emailRedirectOrganizationAlreadyAccepted: "המתנדב כבר התקבל לאירוע",
    emailRedirectOrganizationAlreadyDeclined: "המתנדב דחה אירוע זה בעבר",
    emailRedirectOrganizationDeclined: "המתנדב דחה את האירוע.",
    emailRedirectOrganizationEventStaffed: "האירוע מאויש לגמרי",
    emailRedirectOrganizationInvalidCode: "קוד האבטחה לא חוקי.",
    emailRedirectOrganizationNotInterestedToAccept: "המתנדב אינו מעוניין באירוע ולא הוסף לרשימת המתנדבים שלך",
    emailRedirectOrganizationNotInterestedToDecline: "המתנדב אינו מעוניין באירוע",
    emailRedirectOrganizationOfferAlreadyDeclined: " דחית הצעה הזו בעבר.",
    emailRedirectOrganizationRequestInvalid: "בקשת התנדבות זו כבר לא בתוקף.",
    emailRedirectOrganizationUseDashboard: " קיבלת הצעה זו בעבר. השתמש באיזור האישי כדי לדחות אותו.",
    emailRedirectOrganizationVolunteer: "התנדב",
    emailRedirectUseCredentials: " התחבר לאיזור האישי כדי לצפות באירועים שברשימה.",
    emailRedirectVolunteeredForFilled: "התנדבת בהצלחה אך אירוע זה כבר מלא. אנו ניצור עמך קשר אם נזדקק לסיוע נוסף. תודה רבה",
    emailRedirectVolunteeredSuccessfully: "התנדבת בהצלחה.",
    eventChatMode: "Chat Mode",
    eventDetailActive: "Active",
    eventDetailClosed: "Closed",
    eventDetailEditEvent: "הגדרות אירוע",
    eventDetailInactive: "Inactive",
    eventDetailStatus: "Status",
    eventDetailVolunteers: "מתנדבים",
    eventDetailsChesedChat: "אירוע צ'אט",
    eventDetailsChesedDetails: "פרטי האירוע",
    eventDetailsOrganizationAccept: "קבל",
    eventDetailsOrganizationCancelEvent: "בטל אירוע",
    eventDetailsOrganizationClose: "סגור",
    eventDetailsOrganizationConfirmed: "מאושר",
    eventDetailsOrganizationContactInfo: "פרטי יצירת קשר",
    eventDetailsOrganizationDeactivateEvent: "Deactivate Event",
    eventDetailsOrganizationDecline: "דחה",
    eventDetailsOrganizationDeclined: "נדחה",
    eventDetailsOrganizationEmailToVolunteerSent: "מייל למתנדב נשלח בהצלחה",
    eventDetailsOrganizationEmailsToVolunteersSent: "מיילים למתנדבים נשלחו בהצלחה",
    eventDetailsOrganizationFemale: "נקבה",
    eventDetailsOrganizationInterested: "מעוניין",
    eventDetailsOrganizationMale: "זכר",
    eventDetailsOrganizationNameAgeGender: "שם/גיל/מין",
    eventDetailsOrganizationNoMoreVacancies: "אין יותר משרות פנויות כדי לאשר...",
    eventDetailsOrganizationOngoing: "מתמשך",
    eventDetailsOrganizationOpen: "פתיחה",
    eventDetailsOrganizationReactivateEvent: "Reactivate Event",
    eventDetailsOrganizationSendSuccess: "נשלח בהצלחה",
    eventDetailsOrganizationStaffing: "אנשי צוות:",
    eventDetailsOrganizationStatus: "סטטוס",
    eventJoinCriteria: "Join Criteria",
    eventStatusCancelled: "בוטל",
    eventStatusClosed: "סגור",
    eventStatusDeactivated: "Deactivated",
    eventStatusOpen: "פתוח",
    eventVisibility: "Visibility",
    eventsDisplayNumberDisplaying: "מציג",
    eventsDisplayNumberEvents: "אירועים",
    eventsDisplayNumberOf: "של",
    eventsPosterInfo: "Poster Information",
    eventsPosterTypeErrorMessage: "Please select events poster type",
    eventsPosterTypeText: "Events Poster Type",
    failedOpenDistanceDropdownMessage: "בחר מיקוד כל מנת לאפשר חיפוש במרחב האזורי שלך",
    findVolunteerAlreadySent: "כבר נשלח",
    findVolunteerCategory: "קטגוריה",
    findVolunteerCityZipPhone: "עיר/מיקוד/טלפון",
    findVolunteerEmail: "כתובת מייל",
    findVolunteerEventLoadFailed: "טעינת הפוסט נכשלה",
    findVolunteerFemale: "נקבה",
    findVolunteerFindingVolunteers: "מציאת מתנדבים עבור פוסט",
    findVolunteerHide: "הסתר",
    findVolunteerIncludePastConfirmed: "יש לכלול רק מתנדבים שהתנדבו ואושרו בעבר",
    findVolunteerInvitation: "הזמנה",
    findVolunteerMale: "זכר",
    findVolunteerName: "שם",
    findVolunteerNameAgeGender: "שם/גיל/מין",
    findVolunteerOngoing: "מתמשך",
    findVolunteerPeople: "אנשים",
    findVolunteerReference: "הפניה",
    findVolunteerResults: "תוצאות",
    findVolunteerSelected: "נבחר",
    findVolunteerSend: "שלח",
    findVolunteerSendInvitations: "שלח הזמנות",
    findVolunteerSentTo: "שלח ל-",
    findVolunteerShowHidden: "הצג משתמש מוסתר",
    findVolunteerShowingFirst: "מוצג ראשון",
    findVolunteerStatus: "סטטוס",
    findVolunteerTotalVolunteers: "סך הכל מתנדבים שנמצאו",
    findVolunteerUser: "משתמש",
    findVolunteerUserInfoUpdateFailed: "עדכון פרטי משתמש נכשל",
    findVolunteerVolunteersSelected: "כבר נוצר קשר עם כל המתנדבים שנבחרו להלן",
    findVolunteers: "מצא מתנדבים",
    goToEvent: "עבור לאירוע",
    indexBrowseOpportunities: "עיין בהזדמנויות",
    indexContact: "צור קשר",
    indexContinue: "המשך",
    indexDashboard: "איזור אישי",
    indexDistance: "רוֹחַק",
    indexEditProfile: "(עריכת פרופיל)",
    indexEditProfileMobile: "עריכת פרופיל",
    indexEventView: "הצג האירוע",
    indexFilters: "סנן",
    indexFiltersSelectCategory: "בחר",
    indexFindChesedOpportunity: "מצא הזדמנות חסד מתוך הרשימה והתנדב היום",
    indexFindNear: "מיקוד",
    indexHello: "שלום",
    indexHome: "בית",
    indexJoinVolunteersFirst: "גייס מתנדבים בקהילה שלך",
    indexJoinVolunteersSecond: "הירשם היום",
    indexJustOneChesed: "עם רק אחד חסד",
    indexLogIn: "היכנס",
    indexLogOut: "התנתק",
    indexManageOrganization: "ניהול ארגון",
    indexManageOrganizations: "ניהול ארגונים",
    indexManageVolunteers: "ניהול מתנדבים",
    indexNothingSelected: "לא נבחר שום דבר ",
    indexOpportunities: "הזדמנויות רק חסד אחד",
    indexOrganizationDirectory: "ספריית ארגונית",
    indexSearch: "חיפוש עבור",
    indexSearchForServices: "חפש שירותים להם אתה זקוק באירגונים השונים",
    indexSearchProfessionals: "חפש מתנדבים שהם אנשי מקצוע ",
    indexSearchReset: "נקה",
    indexSearchTerm: "מונחי חיפוש",
    indexSignUp: "הרשם",
    indexTotalEvents: 'נמצאו סה"כ אירועים',
    indexTotalRecords: "Total Records Found",
    indexVolunteer: "התנדב",
    indexVolunteered: "התנדבת. בדוק סטטוס באיזור האישי",
    invalidZipCode: "הזן מיקוד חוקי",
    joinCriteria: "קריטריונים להצטרף",
    languageEnglish: "אנגלית",
    languageEnglishRegister: "אנגלית",
    languageHebrew: "עברית",
    languageHebrewRegister: "עברית",
    languageSelectorEnglish: "English",
    leftMenuChesedFeed: "עדכוני חסד",
    leftMenuPrivateChats: "צ'אטים פרטיים",
    loginCaptchaIncorrect: "Captcha שגוי",
    loginCreateAccount: "צור חשבון",
    loginEmail: "דואר אלקטרוני",
    loginEmailConfirmed: 'כתובת הדוא"ל שלך אושרה. אנא התחבר כדי להשתמש במערכת',
    loginEnterPassword: "הזן סיסמה",
    loginEnterUserName: "הזן שם המשתמש",
    loginForgotPassword: "שכחתי סיסמה",
    loginLogin: "התחבר",
    loginLoginFailed: "הכניסה נכשלה. נסה שוב.",
    loginPassword: "סיסמה",
    loginSecurityCheck: "בדיקת אבטחה",
    loginSignIn: "הרשם",
    loginSuccessfullyVolunteered: "התנדבותך אושרה בהצלחה ",
    loginTitle: "היכנס לרק אחד חסד",
    manageApprovals: "ניהול אישורים",
    manageOrganizationsCityZipPhone: "עיר/מיקוד/טלפון",
    manageOrganizationsEdit: "ערוך",
    manageOrganizationsEditOrganizations: "ערוך תיאור הארגון ",
    manageOrganizationsEmail: 'דוא"ל',
    manageOrganizationsOrganizationName: "שם הארגון",
    manageOrganizationsSearch: "חיפוש",
    manageOrganizationsSuspend: "להשעות",
    manageOrganizationsTotalOrganizations: 'נמצאו סה"כ ארגונים',
    manageOrganizationsWebsite: "אתר אינטרנט",
    manageVolunteersCityZipPhone: "עיר/מיקוד/טלפון",
    manageVolunteersEdit: "עריכה",
    manageVolunteersEditVolunteers: "ערוך פרטי מתנדב",
    manageVolunteersEmail: 'דוא"ל',
    manageVolunteersNameAgeGender: "שם / גיל / מין",
    manageVolunteersSearch: "חיפוש",
    manageVolunteersSuspend: "להשעות",
    manageVolunteersTotalVolunteers: 'נמצאו סה"כ מתנדבים',
    memberAction: "ערוך",
    memberAllEvents: "כל האירועים",
    memberAllEventsIncluding: "כל האירועים (כולל אירועים מבוטלים)",
    memberAllPosters: "כל המפרסמים ",
    memberApply: "ישם",
    memberCategory: "קטגוריה",
    memberConfirmed: "מאושר",
    memberCreateNewEvent: "ליצור פוסט",
    memberDueDate: "תאריך יעד",
    memberDuplicate: "שכפל",
    memberFindVolunteers: "מצא מתנדבים",
    memberFullyStaffed: "מאויש לגמרי",
    memberInterested: "מעוניין",
    memberInternalNotes: "הערות פנימיות",
    memberOfferedByYou: "הצעה שלך",
    memberOngoing: "מתמשך",
    memberRemainingNeeded: "עדיין דרושים ",
    memberSearchInternal: "חיפוש בהערות פנימיות",
    memberSelected: "נבחר",
    memberStatus: "מצב",
    memberTitle: "כותרת",
    memberTotalEvents: "סך הכל הודעות נמצאו",
    memberVolunteersNeeded: "זקוקים מתנדבים",
    memberYourEvents: "הפוסטים שלך",
    members: "חברים",
    multipleSelectModalCancel: "בטל",
    multipleSelectModalClearAll: "מחק הכל",
    multipleSelectModalOk: "אוקיי",
    myProfile: "הפרופיל שלי",
    myProfileAddress: "כתובת",
    myProfileBirthdate: "תאריך לידה",
    myProfileDetails: "פרטים",
    myProfileEmail: 'דוא"ל',
    myProfileEventsVolunteered: "התנדבת לאירועים",
    myProfileFemale: "נקבה",
    myProfileFirstName: "שם פרטי",
    myProfileGender: "מין",
    myProfileLastName: "שם משפחה",
    myProfileMale: "זכר",
    myProfileName: "שם",
    myProfileNoOrganizations: "אין ארגונים",
    myProfileOrganizationMembership: "Organization Membership",
    myProfileOrganizations: "ארגונים",
    myProfilePersonalDetails: "פרטים אישיים",
    myProfilePhoneNumber: "מספר טלפון",
    myProfileSaveChanges: "שמור שינויים",
    myProfileTelephone: "טלפון",
    myProfileTotalChats: 'סה"כ צאטים',
    needToChangePassword: "עליך לשנות את הסיסמה שלך",
    noEvents: "No events",
    noText: "No",
    opportunity: "הזדמנות",
    organizationManagementAddAdministrator: "הוסף מנהל",
    organizationManagementAddMember: "תוסיף חבר",
    organizationManagementAddress: "כתובת",
    organizationManagementAdministrators: "מנהלים",
    organizationManagementAge: "גיל",
    organizationManagementEmail: 'דוא"ל',
    organizationManagementFirstName: "שם",
    organizationManagementIsActive: "פעיל",
    organizationManagementIsApproved: "מורשה",
    organizationManagementLastName: "שם משפחה",
    organizationManagementManageOrganization: "ניהול ארגון",
    organizationManagementMembers: "חברים",
    organizationManagementMissionStatement: "משימה ארגונית",
    organizationManagementMyOrganization: "הארגון שלי",
    organizationManagementNoAdministrators: "אין מנהלי מערכת",
    organizationManagementNoMembers: "No members",
    organizationManagementOpportunity: "הזדמנות",
    organizationManagementOrganizationAdministrators: "מנהלי הארגון",
    organizationManagementOrganizationDetails: "פרטי הארגון",
    organizationManagementOrganizationMembers: "חברי הארגון",
    organizationManagementOrganizationName: "שם ארגון",
    organizationManagementOrganizationalDirectory: "ספרייה ארגונית",
    organizationManagementPhoneNo: "מספר טלפון",
    organizationManagementPhoneNumber: "מספר טלפון",
    organizationManagementSelectOpportunity: "בחר הזדמנות לראות מתנדבים",
    organizationManagementUpdateOrganization: "עדכון הארגון",
    organizationManagementWebsite: "אתר ,אינטרנט",
    pagingNext: "הבא",
    pagingPrevious: "הקודם",
    profilePopDownLogout: "התנתק",
    profilePopDownOrganizationOpportunitiesSettings: "הגדרות הזדמנויות ארגוניות",
    profileSavedMsg: "השינויים נשמרו בהצלחה",
    profileTabChesedAreas: "תחומי חסד",
    profileTabPersonalInformation: "פרטים אישיים",
    readMoreReadMore: "קרא עוד",
    registerChesedAreas: "תחומי חסד",
    registerIndividual: "Individual",
    registerIndividualAccontInfo: "פרטי חשבון אישי",
    registerOrganization: "הארגון",
    registerOrganizationAdd: "הוסף",
    registerOrganizationAddress: "כתובת",
    registerOrganizationAddressOptional: "כתובת (אופציונלי)",
    registerOrganizationAllowToPostEvents: "אפשר ל-JUST ONE CHESED לפרסם אירועים שיצרת גם בדף הפייסבוק שלך",
    registerOrganizationAlreadyHaveAnAccount: "כבר יש לך חשבון?",
    registerOrganizationBack: "חזור",
    registerOrganizationChangePassword: "אני רוצה לשנות את הסיסמה",
    registerOrganizationCharacters: "תווים",
    registerOrganizationClear: "נקה ",
    registerOrganizationCompletedMessage: "הארגון היה רשום בהצלחה, עכשיו מחכה לאישור מנהל. אם יש לך שאלות כלשהן, אנא פנו אלינו ל",
    registerOrganizationCompletedRegistrationCompleted: "רישום הושלמה",
    registerOrganizationConfirmPassword: "אמת סיסמה",
    registerOrganizationConfirmPasswordInvalid: "אימות סיסמה נכשל",
    registerOrganizationContactDirectory: "צור קשר עם מדריך",
    registerOrganizationCreatePassword: "צור סיסמה",
    registerOrganizationDepartment: "מחלקה",
    registerOrganizationDescription: "תיאור",
    registerOrganizationDetailsMinLengthInvalid: " תאר במה אירגונך עוסק במינימום 20 תווים .",
    registerOrganizationDisable: "בטל",
    registerOrganizationDone: "בוצע",
    registerOrganizationEditOrganization: "ערוך פרטי ארגון",
    registerOrganizationEmail: 'דוא"ל',
    registerOrganizationEnable: "אפשר",
    registerOrganizationEnterAddress: "הזן כתובת הארגון",
    registerOrganizationEnterCity: "הזן עיר",
    registerOrganizationEnterDetails: "הזן פרטים",
    registerOrganizationEnterEmail: 'הזן כתובת דוא"ל לכניסה למערכת',
    registerOrganizationEnterName: "הזן שם הארגון",
    registerOrganizationEnterNewPassword: "הזן סיסמה חדשה",
    registerOrganizationEnterOldPassword: "הזן סיסמה ישנה",
    registerOrganizationEnterPhone: "הזן מס' טלפון של הארגון",
    registerOrganizationEnterState: "מדינה",
    registerOrganizationEnterWebsite: "הזן כתובת אתר האינטרנט של הארגון",
    registerOrganizationFacebookPages: "דפי פייסבוק",
    registerOrganizationFax: "פקס",
    registerOrganizationGemachItems: 'אילו פריטים יש לכם בגמ"ח? (יש להוסיף פסיקים בין הפריטים)',
    registerOrganizationGmach: "בניין",
    registerOrganizationGrantSecurityMessage: "לעולם לא נשתף ללא רשותך",
    registerOrganizationHaveGemach: 'יש לנו גמ"ח',
    registerOrganizationImageFormats: "מותר רק jpg ו- png.",
    registerOrganizationImageSize: "גודל הקובץ צריך להיות פחות מ- 5mb",
    registerOrganizationIntegrationDisableFailed: "נסיונך להעלות הזדמנות חסד לדף הפייסבוק נכשל. נסה שוב.",
    registerOrganizationIntegrationEnableFailed: ".נסיונך להפסיק להעלות הזדמנות חסד לדף הפייסבוק נכשל",
    registerOrganizationInvalidEmailFormat: 'פורמט דוא"ל שגוי',
    registerOrganizationInvalidOwner: " בעל הארגון בלבד רשאי להפעיל עמוד פייסבוק זה.",
    registerOrganizationInvalidZipCodeError: "מיקוד ושם עיר אינם תואמים. נא השתמש ב'חיפוש' כדי לקבל נתונים נכונים.",
    registerOrganizationLogoAdded: "לוגו הוסף בהצלחה",
    registerOrganizationLogoUploadFailed: "הוספת לוגו נכשל",
    registerOrganizationLookUp: "חפש",
    registerOrganizationMissionStatement: "תיאור - הצהרת משימה",
    registerOrganizationName: "שם",
    registerOrganizationNextStep: "הצעד הבא",
    registerOrganizationNothingSelected: "לא נבחר שום דבר ",
    registerOrganizationOldPassword: "סיסמה ישנה",
    registerOrganizationOnceChanged: 'לאחר שינוי דוא"ל, יהיה עליך להתחבר שוב עם דוא"ל חדש',
    registerOrganizationOneContactRequired: "מינימום איש קשר אחד נדרש",
    registerOrganizationOrganization: "אִרגוּן",
    registerOrganizationOrganizationCountry: "באיזו מדינה נמצא ארגונך",
    registerOrganizationOrganizationInfo: "פרטי הארגון",
    registerOrganizationOrganizationLanguage: "שפת הארגון",
    registerOrganizationOrganizationLoadFailed: " טעינת הארגון הנוכחית נכשל",
    registerOrganizationOrganizationName: "שם הארגון",
    registerOrganizationOrganizationRegisterType: "Organization Register Type",
    registerOrganizationOrganizationType: "סוג ארגון",
    registerOrganizationPagesUpdateFailed: "עדכון נכשל. נסה שוב.",
    registerOrganizationPassword: "סיסמה",
    registerOrganizationPasswordMinimumLength: "על הסיסמה להיות באורך מינימלי של...",
    registerOrganizationPhone: "טלפון",
    registerOrganizationPhoneNumber: "מספר טלפון",
    registerOrganizationPostalCode: "מיקוד",
    registerOrganizationPostalCodeInvalidDigits: "על המיקוד להכיל ספרות בלבד.",
    registerOrganizationPostalCodeInvalidLength: "אורך המיקוד יהיה בין 5-7 תווים.",
    registerOrganizationQuestion: "יוצר חשבון עבור ארגון?",
    registerOrganizationRegisterOrganization: "רישום הארגון",
    registerOrganizationRegistrationFailed: "הרישום נכשל. נסה שוב.",
    registerOrganizationRemoveLogo: "אני רוצה להסיר את הלוגו",
    registerOrganizationSave: "שמור",
    registerOrganizationSaveFailed: "לא נשמר. נסה שוב.",
    registerOrganizationSaved: "נשמר",
    registerOrganizationSchool: "בית הספר",
    registerOrganizationSelectLogo: "בחר קובץ עבור הלוגו שלך...",
    registerOrganizationSelectYourCountry: "בחר מדינה",
    registerOrganizationSelectYourLanguage: "בחר שפה ",
    registerOrganizationSelected: "נבחר",
    registerOrganizationServiceName: "שם השירות",
    registerOrganizationServices: "השירותים אותם אתה מציע",
    registerOrganizationServicesDescription: "הזן למטה שירותים אותם אתה מציע יחד עם תיאור קצר. דבר זה יעזור לאלה שזקוקים לעזרה לאתר את הארגון ולמצוא בקלות את הסיוע הנידרש.",
    registerOrganizationServicesProvided: "השירותים הניתנים",
    registerOrganizationShul: "בית כנסת",
    registerOrganizationSkip: "דלג",
    registerOrganizationSpecifyPages: "ציין את העמודים בהם  אתה מעונין לפרסם את האירועים שלך",
    registerOrganizationSuccessfullyUpdated: "עודכן בהצלחה.",
    registerOrganizationUploadLogo: "להעלות את הלוגו שלך",
    registerOrganizationWebsiteFormatInvalid: "פורמט האתר שגוי",
    registerOrganizationWebsiteMaxLengthInvalid: "האתר צריך להיות באורך של מקסימום 60 תווים ",
    registerOrganizationWelcomeToTitle: "ברוכים הבאים לרק חסד אחד",
    registerOrganizationWithEmail: "המשך עם מייל",
    registerOrganizationWithExistingAccount: 'יש לי כבר חשבון עם הדוא"ל שלי',
    registerOrganizationWithFacebook: "המשך עם פייסבוק",
    registerOrganizationYourSite: "www.yoursite.com",
    registerQuestion: "חדשים לרק אחד חסד",
    registerRequiredFieldsLegend: "שדה חובה",
    registerSignUpOrganization: "ארגונים יכולים לפרסם את אירועי החסד שלהם על לוח ולחפש ברשימה ממוקדת את המתנדבים שיתאימו לאירועים הללו",
    registerSignUpVolunteer: "הרשם כמתנדב כדי שתוכל לקבל הצעות מארגונים שונים ולהתנדב לאלה שבחרת",
    registerVolunteer: "התנדב",
    registerVolunteerAlreadyHaveAnAccount: "כבר יש לך חשבון?",
    registerVolunteerAsIndividual: "רישום אישי",
    registerVolunteerAsOrganization: "רישום ארגוני",
    registerVolunteerBack: "חזור",
    registerVolunteerCategories: "בחר",
    registerVolunteerCharacters: "תווים",
    registerVolunteerChesedWithin: "מוכן לעשות חסד ב-",
    registerVolunteerChooseGender: "בחר את המגדר שלך ",
    registerVolunteerCity: "עיר",
    registerVolunteerConfirmPassword: "אשר סיסמה",
    registerVolunteerConfirmPasswordInvalid: " סיסמה אינה זהה",
    registerVolunteerCreatePassword: "צור סיסמה",
    registerVolunteerDatabaseOfProfessionals: "אנחנו בונים מאגר נתונים רחב של אנשי מקצוע. עזור לנו להבין כיצד היית רוצה לעזור בתוך התחום שלך",
    registerVolunteerDateOfBirthInvalid: "תאריך הלידה אינו חוקי",
    registerVolunteerDone: "סיום",
    registerVolunteerEmail: 'דוא"ל',
    registerVolunteerEnterBirthDate: "הזן תאריך לידה",
    registerVolunteerEnterEmail: 'הזן דוא"ל',
    registerVolunteerEnterFullName: "הזן את שמך המלא",
    registerVolunteerEnterLocation: "מיקום",
    registerVolunteerEnterPhone: "הזן מס' הטלפון ",
    registerVolunteerFemale: "נקבה",
    registerVolunteerFirstName: "שם פרטי",
    registerVolunteerGrantSecurityMessage: "לעולם לא נשתף ללא רשותך",
    registerVolunteerInvalidEmailFormat: 'פורמט הדוא"ל שגוי',
    registerVolunteerInvalidZipCodeError: "מיקוד ושם עיר אינם תואמים. נא השתמש ב'חיפוש' כדי לקבל נתונים נכונים.",
    registerVolunteerLastName: "שם משפחה",
    registerVolunteerLoginToJOC: "התחבר ל-Just One Chesed כדי לראות את לוח החסד שלך והתנדב לאירועים",
    registerVolunteerLookUp: "חפש",
    registerVolunteerMale: "זכר",
    registerVolunteerNextStep: "השלב הבא",
    registerVolunteerNothingSelected: "לא נבחר שום דבר ",
    registerVolunteerOccupation: "מקצוע",
    registerVolunteerOccupationDetails: "פרטי מקצוע ",
    registerVolunteerPassword: "סיסמה",
    registerVolunteerPasswordMinimumLength: "סיסמה חייבת להיות באורך מינימלי של",
    registerVolunteerPostEventsQuestion: "Are You going to post events?",
    registerVolunteerPostalCode: "מיקוד",
    registerVolunteerPostalCodeInvalidDigits: "על המיקוד להכיל ספרות בלבד",
    registerVolunteerPostalCodeInvalidLength: "אורך המיקוד יהיה בין 5-7 תווים.",
    registerVolunteerProfessionalVolunteers: "מתנדבים מקצועיים",
    registerVolunteerQuestion: "יצירת חשבון עבור מתנדב?",
    registerVolunteerRegistration: "רישום",
    registerVolunteerRegistrationCompleted: "הרישום הושלם",
    registerVolunteerRegistrationFailed: "הרישום נכשל. נסה שוב.",
    registerVolunteerRequiredFieldsMustBeFilled: "All required fields must be filled",
    registerVolunteerSelect: "חסד",
    registerVolunteerSelectChesedAreas: "בחר תחום של אירוע חסד ",
    registerVolunteerSelectChesedAreasFullText: "נא לבחור את תחומי חסד שמעניינים אותך. נשתמש בבחירות שלך כדי לשלוח לך הודעות על הזדמנויות חדשות. אם אינך מעוניין לקבל התראות בשלב זה, לחץ על סיום",
    registerVolunteerSelectOneChesedArea: "אנא בחר תחום חסד אחד לפחות",
    registerVolunteerSelectRadius: "נא בחר עד איזה מרחק ממיקומך הנוכחי אתה מוכן להתנדב",
    registerVolunteerSelectYourCountry: "בחר את ארץ המגורים שלך",
    registerVolunteerSelectYourLanguage: "בחר שפה מועדפת",
    registerVolunteerSelected: "נבחר",
    registerVolunteerSpecialization: "התמחות",
    registerVolunteerStep1: "שלב 1",
    registerVolunteerStep2: "שלב 2",
    registerVolunteerStep3: "שלב 3",
    registerVolunteerStep4: "שלב 4",
    registerVolunteerTextReminders: "נא לשלוח לי טקסט עם תזכורות על האירועים שלי למספר הזה",
    registerVolunteerUsedEmail: "Email is already used",
    registerVolunteerVolunteer: "תחומי",
    registerVolunteerWelcomeToTitle: "ברוכים הבאים לרק חסד אחד",
    registerVolunteerWithEmail: "המשך עם מייל",
    registerVolunteerWithFacebook: "המשך עם פייסבוק",
    searchForServicesDistance: "רוֹחַק",
    searchForServicesFindNear: "מיקוד",
    searchForServicesGemachItems: 'פריטים מגמ"ח',
    searchForServicesNothingSelected: "לא נבחר שום דבר ",
    searchForServicesOR: "or",
    searchForServicesOnlyGemach: 'חפש רק בגמ"ח',
    searchForServicesOrganizationType: "סוג ארגון",
    searchForServicesSearch: "חפש",
    searchForServicesSearchForOrganizations: 'חפש ארגונים המציעים שירותים אלה או פריטים מגמ"ח...',
    searchForServicesSelectOrganizationType: "בחר סוג",
    searchForServicesState: "Enter State",
    searchForServicesTotalOrganizations: 'נמצאו סה"כ ארגונים',
    searchForServicesTypeTitle: "סוּג",
    searchForServicesWebsite: "אתר אינטרנט",
    searchProfessionalsCityZipPhone: 'עיר / מיקוד / טלפון',
    searchProfessionalsEmail: 'דוא"ל',
    searchProfessionalsFindNear: "מיקוד",
    searchProfessionalsNameAgeGender: "שם / גיל / מגדר",
    searchProfessionalsNameEmail: 'שם/דוא"ל',
    searchProfessionalsNothingSelected: "לא נבחר שום דבר ",
    searchProfessionalsOccupation: "מקצוע",
    searchProfessionalsReference: "הפניה",
    searchProfessionalsResults: "תוצאות",
    searchProfessionalsSearch: "חיפוש",
    searchProfessionalsSearchProfessionals: "חיפוש אנשי מקצוע",
    searchProfessionalsShowingFirst: "הצג ראשון",
    searchProfessionalsSpecialization: "התמחות",
    searchProfessionalsState: "Enter State",
    searchProfessionalsTotalProfessionals: 'נמצאו סה"כ מומחים',
    selectOpportunityToSeeVolunteers: "בחר הזדמנות לראות מתנדבים",
    signinVolunteerWithEmail: 'התחבר עם דוא"ל',
    signinVolunteerWithFacebook: "התחבר עם פייסבוק",
    subCategoriesModalCancel: "בטל",
    subCategoriesModalClearAll: "מחק הכל",
    subCategoriesModalOk: "אוקיי/בסדר",
    title: "שם",
    topMenuVisitMyProfile: "בקר בפרופיל שלי",
    updateOrganization: "עדכון הארגון",
    userDetails: "פרטי המשתמש",
    volunteerCategoryCenterText1: "בחר",
    volunteerCategoryCenterText2: "תחומי",
    volunteerCategoryCenterText3: "חסד",
    volunteerMsgThankyou: "{0} תודה על התנדבות עבור",
    volunteerMsgWaitForApproval: "This opportunity requires a response from the organizer. You should hear from them shortly.",
    yesText: "Yes",
    zipCodeLookUpInvalidBuildingNumber: "מספר בית/בנין לא קיים",
    zipCodeLookUpModalApply: "ישם",
    zipCodeLookUpModalBuildingNumber: "בחר מספר בית",
    zipCodeLookUpModalCancel: "בטל",
    zipCodeLookUpModalCity: "בחר עיר",
    zipCodeLookUpModalClearAll: "נקה הכל",
    zipCodeLookUpModalNoBuildingMatchInfo: "אם אין התאמה, נא בחר את הבניין הכי קרוב ",
    zipCodeLookUpModalStartTyping: "התחל להקליד",
    zipCodeLookUpModalStreet: "בחר רחוב",
    zipCodeLookUpModalTitle: "חפש מיקוד",
    zipCodeLookUpModalZipCode: "מיקוד",
    zipCodeLookUpNoResults: "אין תוצאות",
    eventDetails: 'event details',
    newOpportunityIDF: "חיילים",
    newOpportunityFinancing: "מימון",
    newOpportunityMothersHelper: "שמרטף",
    newOpportunityFoodCooking: "מזון / בישול",
    newOpportunityEM: "בידור / מוזיקה",
    newOpportunityMediaTech: "מדיה / טכנולוגיה",
    newOpportunityHachanasOrchim: "הכנסת אורחים",
    newOpportunityTefillah: "תפילה",
    newOpportunityTorah: "תורה",
    newOpportunityDriving: "נהיגה /טרמפים",
    newOpportunityTutoringLessons: "למידה / שיעורים פרטיים",
    newOpportunityMentoring: "יעוץ /הדרכה",
    newOpportunityManPower: "כוח אדם",
    newOpportunityCelebrationsEvents: "אירועים / חגיגות",
    newOpportunityHolidayHelp: "לקראת החג",
    newOpportunityBikurCholim: "ביקור חולים",
    newOpportunitySeniorHelp: "עזרה לקשישים",
    newOpportunityNewOlim: "עולים חדשים",
    settingLanguages: "שפה",
    myProfileSelectBirthDate: "בחר תאריך לידה",
    menuItemSettings: "הגדרות"
  },
});